### PR TITLE
support for invidio.us links

### LINKED ISSUE #123: Support invidious
Invidious is an alternative front-end for YouTube, and it'd be neat if NewPipe supported it!

https://github.com/omarroth/invidious

### PR DESCRIPTION
**Pull request by anoymouserver**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

I adapted the link support of `hooktube.com` for `invidio.us` which closes #123 and refs TeamNewPipe/NewPipe#1900.

### CODE REVIEW

**Comment by TobiGr** [comment]
Hello @anoymouserver,
thanks for taking a look at invidious support. To test your extractor changes with NewPipe, you can follow our [documentation](https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/).

**Comment by wb9688** [comment]
In NewPipe you've to add invidio.us to the manifest for it to work though.

**Comment by anoymouserver** [comment]
Sorry, but currently I can't install Android Studio here, so it will be kinda difficult to test my changes. I was hoping that some of you could do this. 😊

@wb9688 I've already done this in TeamNewPipe/NewPipe#1900.

The Travis build failed while running `YoutubeSearchExtractorDefaultTest` which I haven't even touched..?

**Comment by wb9688** [comment]
Ah, I didn't saw that. Btw it's normal that Travis fails, I think it's
because YouTube blocks automated servers like that.

**Comment by theScrabi** [comment]
> Sorry, but currently I can't install Android Studio here,  so it will be kinda difficult to test my changes. I was hoping that some  of you could do this.
--

issue has been resolved, extractor is compatible with frontend again.

**Comment by theScrabi** [comment]
closing in favour of https://github.com/TeamNewPipe/NewPipeExtractor/pull/132

**Pull request closed without merging**
