### PR TITLE
[WiP] Improve README

### PR DESCRIPTION
**Pull request by wb9688**
I've started working on improving the README as per #33, but as you might see it isn't done yet, so please don't merge it yet.

What things will I need to add?

Now I think about it again, wouldn't it be better to use Javadoc for the documentation?

### CODE REVIEW

**Comment by TheAssassin** [comment]
You removed all information about what the extractor is/does (https://github.com/TeamNewPipe/NewPipeExtractor/pull/34/files#diff-04c6e90faac2675aa89e2176d2eec7d8L5). People looking at the repository probably have no clue about what the extractor does. We should add some information about that again, maybe a bit more elaborate.

**Comment by theScrabi** [comment]
I agree with @TheAssasine we should leave a connection to newpipe frontend.

**Comment by wb9688** [comment]
I forgot that, that's why I asked if I forgot something. Would a sentence
like "It is a core component of NewPipe, but could be used independently."
OK? Btw what do you think about the following?

>wouldn't it be better to use Javadoc for the documentation?

**Comment by theScrabi** [comment]
Javadoc might not be such a idea.

Also its no a core component of NewPipe its THE core component of NewPipe :)

**Comment by wb9688** [comment]
@theScrabi: Why would Javadoc not be such a great idea?

Won't PipeCast also be a core component?

**Comment by theScrabi** [comment]
*such a bad idea

Sorry just woke up.

**Pull request merged**
