### PR TITLE
[YouTube] Always get the best thumbnail resolution

### PR DESCRIPTION
**Pull request by FireMasterK**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

### CODE REVIEW

**Comment by tsiflimagas** [comment]
This seems to be giving an error for channels with no banner.

**Comment by XiangRongLin** [comment]
1. What is the reasoning behind always getting the best resolution?
2. Would this not lead to a higher network usage, which would not be desired on mobile data/bad internet connection?

**Comment by TobiGr** [comment]
The goal should be to provide all image sizes and let the client choose the resolution it needs. See #268

**Comment by FireMasterK** [comment]
I'll close this as this doesn't solve the problem in that case.

**Pull request closed without merging**
