### PR TITLE
setter getter method for bookmarked subscription

### PR DESCRIPTION
**Pull request by 123vipulj**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

setter getter method for bookmarked subscription

### CODE REVIEW

**Comment by theScrabi** [comment]
pelase add furthter description in of your pullrequest, and don't just put all information into the title.

**Comment by theScrabi** [comment]
I don't even know what you are trying to achieve with your PR.

**Comment by 123vipulj** [comment]
theScrabi You can see my pull request in newpipe repo where i added bookmark icons  in subscription tab which needed helper method . So i added in it . It will help in decide which subscription is bookmarked  by user .

**Comment by TobiGr** [comment]
@123vipulj You are trying to store information in the extractor which has been gathered by the frontend. To store whether a user subscribed to a channel or not, you need to make changes in the frontend, but not here. 
The extractor is an extra library which is used by other projects, too. Therefore, we'd like to keep it clean and not mix up stream and user related information.

**Comment by 123vipulj** [comment]
> To store whether a user subscribed to a channel or not, you need to make changes in the frontend, but not here.

**TobiGr**  it makes it nearly impossible .
Please look at it code one more time

**SubscriptionEntity.java**

    @Ignore
    public ChannelInfoItem toChannelInfoItem() {
        ChannelInfoItem item = new ChannelInfoItem(getServiceId(), getUrl(), getName());
        item.setThumbnailUrl(getAvatarUrl());
        item.setSubscriberCount(getSubscriberCount());
        item.setDescription(getDescription());
        item.setBookmark(getBookmarks());
        return item;
    }`

    @Ignore
    public static SubscriptionEntity from(@NonNull ChannelInfo info) {
        SubscriptionEntity result = new SubscriptionEntity();
        result.setServiceId(info.getServiceId());
        result.setUrl(info.getUrl());
        result.setData(info.getName(), info.getAvatarUrl(), info.getDescription(), info.getSubscriberCount(),result.getBookmarks());
        return result;
    }`

I am pasing data in **ChannelInfoItem** from subscription database.
In **ChannelMiniInfoItemHolder.java**

    @Override
    public void updateFromItem(final InfoItem infoItem) {
        if (!(infoItem instanceof ChannelInfoItem)) return;
        final ChannelInfoItem item = (ChannelInfoItem) infoItem;


        itemTitleView.setText(item.getName());
        itemAdditionalDetailView.setText(getDetailLine(item));

       //This code will set bookmark image to respected position of subcription
        if(item.getBookmark() == 1){
            itemBookmarkBtn.setBackground(ContextCompat.getDrawable(itemView.getContext(),R.drawable.bookmarked));
        }else if (item.getBookmark() == 0){
            itemBookmarkBtn.setBackground(ContextCompat.getDrawable(itemView.getContext(),R.drawable.bookmark));
        }
`

Data is passing to **updateFromItem()** method from Adapter Class **InfoListAdapter**   and ChannelInfoItem object associated with respected infoitem .Thats why it is easy to determine from that which subscription subscribed by user;

>  you need to make changes in the frontend, but not here.

If i change one codebase in frontend .This will lead me to change to another code. If i make logic to determine **item.getBookmark()** is subscribed or not .It will be buggy because data is passing one by one in   **updateFromItem()** method.

What if i make another constructor in **ChannelInfoItem.java** class .Something like that .

     private String description;
     private long subscriberCount = -1;
     private long subscriberCount = -1;
     private long streamCount = -1;
     private long streamCount = -1;
 
     private long bookmark;
 
 
     public ChannelInfoItem(int serviceId, String url, String name) {
     public ChannelInfoItem(int serviceId, String url, String name) {
         super(InfoType.CHANNEL, serviceId, url, name);
         super(InfoType.CHANNEL, serviceId, url, name);
     }
     }
 
     public ChannelInfoItem(InfoType infoType, int serviceId, String url, String name, String description, long subscriberCount, long streamCount) {
         super(infoType, serviceId, url, name);
         this.description = description;
         this.subscriberCount = subscriberCount;
         this.streamCount = streamCount;
     }
 
     public ChannelInfoItem(InfoType infoType, int serviceId, String url, String name, String description, long subscriberCount, long streamCount, long bookmark) {
         super(infoType, serviceId, url, name);
         this.description = description;
         this.subscriberCount = subscriberCount;
         this.streamCount = streamCount;
         this.bookmark = bookmark;
     }
     }`

Constructor with having bookmark parameter will not affect entire ecosystem except two class **SubscriptonEntity** and **ChannelMiniInfoItemHolder** . I think it will be safe way to that.

**Comment by 123vipulj** [comment]
I am ongoing to make  grouped and categorized wise subscription feature. Where user can create custom group of subscription such as news , arts , tutorials group and will trying to make custom notification whenever new videos is come from grouped subscription . So ,add some code snippet in extracter will help me.

**Pull request closed without merging**
