### PR TITLE
[Soundcloud] Update hardcoded client id

### PR DESCRIPTION
**Pull request by XiangRongLin**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

In response to: https://github.com/TeamNewPipe/NewPipeExtractor/runs/4766073255?check_suite_focus=true#step:5:304
I personally find the tests bad, because they will regulary break the CI pipeline. But thats my personal opinion

### CODE REVIEW

**Comment by opusforlife2** [comment]
> I personally find the tests bad because they will regulary break the CI pipeline

Is it possible to have a separate test + CI run just for the client ID?

**Comment by TiA4f8R** [comment]
The hardcoded client id has been updated with #768. Closing.

**Comment by opusforlife2** [comment]
> https://github.com/TeamNewPipe/NewPipeExtractor/pull/777#issuecomment-1012273843

Yes or no? Anyone?

**Comment by XiangRongLin** [comment]
> Is it possible to have a separate test + CI run just for the client ID?

@opusforlife2 Yes, but it requires time to seperate it out properly. If you have the time feel free to do it.

**Comment by opusforlife2** [comment]
I have no idea how. xD But now that I know it's possible, we can open an issue for this.

**Pull request closed without merging**
