### PR TITLE
[YouTube] Workaround again 403 HTTP issues on the ANDROID InnerTube client and fix stream tests

### PR DESCRIPTION
**Pull request by AudricV**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe). No, but I tested my changes with a `visitorData` on which the 403 HTTP issues was present before and they didn't occur anymore with the new parameters.

This PR works around again 403 HTTP issues when getting streams from the `ANDROID` InnerTube client, by using new parameters to bypass this client's integrity checks.

These parameters are the only ones currently known to bypass the 403 HTTP issues, as the ones of stories (and the base of the shorts ones) do not work anymore (currently A/B tested), which may be related to end of this format on the service.

I also fixed stream test failures, which were not present in the existing mocks but were present when I updated stream mocks (required due to the player parameters update of the `ANDROID` client).

I had especially to change the video used in `YoutubeStreamExtractorDefaultTest.PublicBroadcasterTest` test class, as the channel Dinge Erklärt – Kurzgesagt is not affiliated with a public broadcast channel anymore.

I chose the 3 million subscribers thanks video from ARTE French YouTube channel (`cJ9to6EmElQ`) as a replacement.

Fixes TeamNewPipe/NewPipe#10174.

### CODE REVIEW

**Comment by SavSanta** [comment]
Is there a samp apk while waiting for checks? 

Also if this is A/B related how would you suggest testing this. I've been getting the errors lately but I also have 2 other older previous debug Newpipe versions (for various issues). When the 403 pops up I can share the video to one of those and generally the issue doesn't appear.

Cheers

**Review by Stypox — APPROVED** [review]
If this works then LGTM, it's only a small change that makes sense

**Comment by joshuabengal** [comment]
> This PR works around again 403 HTTP issues when getting streams from the `ANDROID` InnerTube client, by using new parameters to bypass this client's integrity checks.
> 
> These parameters are the only ones currently known to bypass the 403 HTTP issues, as the ones of stories (and the base of the shorts ones) do not work anymore (currently A/B tested), which may be related to end of this format on the service.

Works great, my question is how/where was the new param setting ("CgIQBg") found? I could not find any list of valid param settings in the YouTube API documentation. 

Basically if at some point CgIQBg stops working, where do we look for another valid param value?

**Comment by Bashiraljomma** [comment]
> * [x] لقد قرأت بعناية [إرشادات المساهمة](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) وأوافق عليها.
> * [ ] لقد اختبرت واجهة برمجة التطبيقات (API) ضد [NewPipe](https://github.com/TeamNewPipe/NewPipe) . لا، لكنني اختبرت تغييراتي باستخدام `visitorData`مشكلات HTTP 403 التي كانت موجودة من قبل ولم تعد تحدث مع المعلمات الجديدة.
> 
> يعمل هذا العلاقات العامة مرة أخرى على حل 403 مشكلات HTTP عند الحصول على التدفقات من `ANDROID`عميل InnerTube، وذلك باستخدام معلمات جديدة لتجاوز عمليات التحقق من سلامة هذا العميل.
> 
> هذه المعلمات هي الوحيدة المعروفة حاليًا بتجاوز مشكلات HTTP 403، نظرًا لأن تلك القصص (وقاعدة القصص القصيرة) لم تعد تعمل (يتم اختبار A/B حاليًا)، والتي قد تكون مرتبطة بنهاية هذا التنسيق على الخدمة.
> 
> لقد قمت أيضًا بإصلاح حالات فشل اختبار البث، والتي لم تكن موجودة في النماذج الحالية ولكنها كانت موجودة عندما قمت بتحديث نماذج البث (مطلوب بسبب تحديث معلمات المشغل للعميل `ANDROID`).
> 
> اضطررت بشكل خاص إلى تغيير الفيديو المستخدم في `YoutubeStreamExtractorDefaultTest.PublicBroadcasterTest`فصل الاختبار، حيث أن قناة Dinge Erklärt – Kurzgesagt لم تعد تابعة لقناة بث عامة بعد الآن.
> 
> I chose the 3 million subscribers thanks video from ARTE French YouTube channel (`cJ9to6EmElQ`) as a replacement.
> 
> Fixes [TeamNewPipe/NewPipe#10174](https://github.com/TeamNewPipe/NewPipe/issues/10174).

**Comment by Bashiraljomma** [comment]
Kjftgh

**Comment by Pheb62** [comment]
0.25.2 - abort video after a second is back again.

**Pull request merged**
