### PR TITLE
Support new YouTube JSON scheme

### LINKED ISSUE #439: YouTube did not provide player config even after three attempts
[444.har.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5433261/444.har.zip)
The above is the information I collected when I made a mistake. I hope it will be helpful to you. If you need my cooperation, please reply to me in time.

### PR DESCRIPTION
**Pull request by B0pol**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

fixes TeamNewPipe/NewPipe#4572 fixes #439
@Stypox @TobiGr

### CODE REVIEW

**Comment by opusforlife2** [comment]
Yay!

**Comment by opusforlife2** [comment]
^ 4572, not 4752.

**Comment by xibr** [comment]
I have tested this changes and I got this error 
`
failed to find pattern ""assets":.+?"js":\s*("[^"]+")
`

**Comment by opusforlife2** [comment]
Maybe try both patterns twice before moving on just to be safe?

**Review by Stypox — COMMENTED** [review]
This isn't a proper fix, it only replaces the "retry multiple times" code with "try a different way", both of which are workarounds. I'll try to see if there is another way to really fix this

**Comment by B0pol** [comment]
@xibr I did some tests. I could reproduce your issue twice time in 300 tries. Before this patch, it's about 15 in 100 tries (BUT each exception try is already 3 tries, then more like 45-60 failed attempts) (with the same video though).

@Stypox So what I did is try to get info some missing info with new file from embedIt seemed to work everytime but I did not test enough, thank you @xibr . It is still way more reliable as I said before, but yeah it's not a proper fix.

Here is what it tries to find pattern when it fails / when it is normal
[newpipe.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5441321/newpipe.zip)

**Comment by Stypox** [comment]
@B0pol the player url is there inside the fail html: `"jsUrl": "/s/player/4a1799bd/player_ias.vflset/en_GB/base.js"`. It's just a matter of finding it, but it is there :-D

**Comment by Stypox** [comment]
I think this can be solved completely by caching the player url or even the deobfuscation code. I was able to use the player url from your HTMLs (it's the same in both of them: `/s/player/4a1799bd/player_ias.vflset/en_GB/base.js`) to deobfuscate the stream urls of requests made by me just now and of the HAR in #439

**Comment by Stypox** [comment]
Here is an APK with a hardcoded player js URL. For me it works perfectly. Obviously the URL probably will change over time, but just as a check I'm uploading this APK. @opusforlife2 does this also work in India, where YouTube might be doing things differently than in Europe? @xibr could you also test?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5441529/app-debug.zip)

**Comment by opusforlife2** [comment]
Werks ^. And it is indeed faster. :D

**Comment by FireMasterK** [comment]
Yep, can confirm it works in India :)

**Comment by opusforlife2** [comment]
@FireMasterK Oh wow. I just noticed you're the one hosting that new Invidious instance I use. Thanks for that. ;)

**Comment by B0pol** [comment]
I pushed a fixed for
> failed to find pattern ""assets":.+?"js":\s*("[^"]+")
Without hardcoding URL as @Stypox did previously.

New debug APK: [newpipe-FIXED.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5442111/newpipe-FIXED.zip)
BTW, you may encounter bug https://github.com/TeamNewPipe/NewPipe/issues/4653, just close it when it appears

**Comment by geckolinux** [comment]
> New debug APK: [newpipe-FIXED.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5442111/newpipe-FIXED.zip)

I was getting `Could not load decryption code for the Youtube service` for every video on a new install (CarbonROM Android 10). It was working normally on my previous installation of anothet Android 10 ROM. This debug APK fixes it, thanks!

**Comment by Tetriser** [comment]
Having the exact same problem here, now using the temporary APK.

**Comment by xibr** [comment]
> I pushed a fixed for
> > failed to find pattern ""assets":.+?"js":\s*("[^"]+")
> Without hardcoding URL as @Stypox did previously.
> 
> New debug APK: [newpipe-FIXED.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5442111/newpipe-FIXED.zip)
> BTW, you may encounter bug https://github.com/TeamNewPipe/NewPipe/issues/4653, just close it when it appears

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=O0StKlRHVeE
* __Content Country:__ KR
* __Content Language:__ ko
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUAETG3:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get name
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getName(YoutubeStreamInfoItemExtractor.java:98)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.isAd(YoutubeStreamInfoItemExtractor.java:81)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:39)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:94)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getRelatedStreams(YoutubeStreamExtractor.java:601)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getRelatedVideosOrLogError(ExtractorHelper.java:32)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:328)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by xibr** [comment]
>  @xibr could you also test?
> Btw, with this APK it even takes less time to load videos :-D
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5441529/app-debug.zip)
> 

Works fine so far.

**Comment by 71walceli** [comment]
I just installed the debug build.  and even restored settings from stable one. Hereby I confirm it's working fine. Thanks a lot.

**Comment by xibr** [comment]
I have tested two apk files provided by @ Stypox and @ B0pol and it works fine no errors yet shown.  There is one file error provided by @ B0pol but it never appears again after removing cache.
the crash log in my comment above.

**Comment by FireMasterK** [comment]
I got this error on B0pol's build, I'm not sure if it's related to this tho.

## Exception
* __User Action:__ requested comments
* __Request:__ https://m.youtube.com/watch?v=_83KqwEEGw4
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:97)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:52)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$Xyj84g1UeNZqX9LVYNvWZsdT-kI.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:95)
	... 30 more

```
</details>
<hr>

**Comment by B0pol** [comment]
@xibr Could not reproduce the issue (I tried 100 times). If you can reproduce, please [provide a HAR file](https://github.com/TeamNewPipe/NewPipe/wiki/Additional-Debugging-Info)


@FireMasterK it's not related, we already know this issue

**Comment by xibr** [comment]
@B0pol Well, so far I can't reproduce, if I can reproduce I will attach a HAR file.

This fix works fine.

**Comment by fareszr** [comment]
> I pushed a fixed for
> 
> > failed to find pattern ""assets":.+?"js":\s*("[^"]+")
> > Without hardcoding URL as @Stypox did previously.
> 
> New debug APK: [newpipe-FIXED.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5442111/newpipe-FIXED.zip)
> BTW, you may encounter bug [TeamNewPipe/NewPipe#4653](https://github.com/TeamNewPipe/NewPipe/issues/4653), just close it when it appears

Can confirm this fixes all the issues with the current release.

S10+ LOS 17.1

**Comment by vrhikaru** [comment]
> I pushed a fixed for
> 
> > failed to find pattern ""assets":.+?"js":\s*("[^"]+")
> > Without hardcoding URL as @Stypox did previously.
> 
> New debug APK: [newpipe-FIXED.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5442111/newpipe-FIXED.zip)
> BTW, you may encounter bug [TeamNewPipe/NewPipe#4653](https://github.com/TeamNewPipe/NewPipe/issues/4653), just close it when it appears

It's work for me, I tested on Nexus 6P, from Taiwan.

**Review by Stypox — APPROVED** [review]
Not perfect, but perfectly valid for a hotfix. Thank you!

**Review by cion49235 — APPROVED** [review]

**Pull request merged**
