### PR TITLE
Upgrade to Gradle 7.1.1

### PR DESCRIPTION
**Pull request by TacoTheDank**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [N/A] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [N/A] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Handles https://github.com/TeamNewPipe/NewPipeExtractor/pull/682, which in turn closes https://github.com/TeamNewPipe/NewPipe/issues/6651.

### 1st commit
I don't really know what to do about the maven publishing, or if anything needs to be done or added, because this feels too easy. We don't have any existing publishing setup anywhere, so idk.

I updated Gradle to 7.1.1 using git bash.

### 2nd commit
Saw some things I wanted to improve, so I did that.

### CODE REVIEW

**Comment by Stypox** [comment]
> I don't really know what to do about the maven publishing, or if anything needs to be done or added, because this feels too easy. 

Just check if JitPack works on your latest commit, i.e. `implementation "com.github.TacoTheDank:NewPipeExtractor:10f17f37564364de85912024b3a274cedf1143fb"`

**Comment by TacoTheDank** [comment]
@Stypox It, uh, doesn't... https://jitpack.io/com/github/TacoTheDank/NewPipeExtractor/10f17f3756/build.log

I don't work with maven publishing stuff, I have no idea how it works. Someone will probably have to help me out here, as I'm not familiar with the JDoc stuff. I allow commits to forks, so they can be added on to this PR.

**Comment by TobiGr** [comment]
[Here is the jitpack log.](https://jitpack.io/com/github/TacoTheDank/NewPipeExtractor/10f17f3756/build.log) The build is successful, however no build artifacts are found.
<details><summary>The interesting part of the logs</summary>

``` log
BUILD SUCCESSFUL in 6s
10 actionable tasks: 7 executed, 3 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-07-21T15:29:48.830579556Z
Exit code: 0

ERROR: No build artifacts found
```

</details>

For comparison, [here is the NewPipe Extractor 0.21.6 log](https://jitpack.io/com/github/TeamNewPipe/NewPipeExtractor/v0.21.6/build.log)

**Comment by TacoTheDank** [comment]
I have an idea actually that involves changing artifact names. However, I have to go to work now, so I'll try it out when I get back.

**Comment by TacoTheDank** [comment]
Ok so it didn't work. Nevermind.

**Comment by litetex** [comment]
I don't know if this helps but I found that on Stackoverflow:
https://stackoverflow.com/questions/67599438/gradle-7-and-jitpack-io-runs-into-error-during-publish

**Comment by TacoTheDank** [comment]
@litetex Getting
```
A problem occurred configuring project ':extractor'.
> Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
```

when trying those solutions...

**Comment by litetex** [comment]
@litetex 
I could fix it using https://github.com/litetex/NewPipeExtractor/commit/654857a62d4fb572d18dacb6f4ee0d47b920aeac
Jitpack-log: https://jitpack.io/com/github/litetex/NewPipeExtractor/654857a62d4fb572d18dacb6f4ee0d47b920aeac/build.log

https://stackoverflow.com/a/42977330 did the trick

**Comment by TacoTheDank** [comment]
@litetex Bless you :P

**Comment by TacoTheDank** [comment]
Rebased on upstream.

**Review by TobiGr — APPROVED** [review]
Thank you @TacoTheDank  & @litetex

**Pull request merged**
