### PR TITLE
Add getMixUrl method to StreamExtractors

### PR DESCRIPTION
**Pull request by Stypox**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

I added the `getMixUrl(MixType)` method to every `StreamExtractor`, along with an `enum` for mix types (video, music, channel, album), following https://github.com/TeamNewPipe/NewPipe/issues/3583#issuecomment-876712109. This PR is a draft and still needs work, also the frontend UI is still a TODO, but feel free to give feedback ;-).

- Youtube video with mix: https://www.youtube.com/watch?v=l-mPoJe8wZQ
- Youtube video mix: https://www.youtube.com/watch?v=l-mPoJe8wZQ&list=RDl-mPoJe8wZQ
- Youtube music mix: https://music.youtube.com/watch?v=l-mPoJe8wZQ&list=RDAMVMl-mPoJe8wZQ
- Youtube channel mix: ~~https://www.youtube.com/watch?v=l-mPoJe8wZQ&list=RDCMUCf5q0cbFOLbphljteZ9d4Pw~~ (I don't know why it doesn't work, this needs investigation) https://www.youtube.com/watch?v=9iHM6X6uUH8&list=RDCMUC_aEa8K-EOJ3D6gOs7HcyNg
- Soundcloud track with station (click the More button): https://soundcloud.com/jim-yosef/jim-yosef-firefly-ncs-release
- Soundcloud station (still unsupported by the extractor): https://soundcloud.com/stations/track/jim-yosef/jim-yosef-firefly-ncs-release
- Bandcamp track with related album (in NewPipe just considered as a playlist): https://jimyosef.bandcamp.com/track/dawn

Fixes https://github.com/TeamNewPipe/NewPipe/issues/3583
Fixes https://github.com/TeamNewPipe/NewPipe/issues/3250

### CODE REVIEW

**Comment by Stypox** [comment]
@XiangRongLin YouTube mixes seem to work randomly: for some videos they exist, for some others they do not. I'd switch to the other approach of returning a `MultiInfoItemsCollector` from `streamInfo.getRelatedItems()`, with available mixes and all other related videos. The only problem here is that strings cannot be translated, but I'd just use the mix name provided by youtube and call it a day (e.g. "Mix – NoCopyrightSounds"), since that's the name used in MixPlaylistExtractor too.

**Comment by opusforlife2** [comment]
Yay! Youtube Music mixes! 💃

**Comment by opusforlife2** [comment]
Youtube Music mixes...

**Comment by Stypox** [comment]
Closing in favor of #788

**Pull request closed without merging**
