### PR TITLE
Add support for getting uploader URL

### PR DESCRIPTION
**Pull request by wb9688**
As per TeamNewPipe/NewPipe#814, but I haven't tested it though.

### CODE REVIEW

**Comment by coffeemakr** [comment]
I think you will have to add the field also to the `StreamInfoItem` and  set the field in the `StreamInfoItemCollector` like this: acf05b748cc367eec9e58dd6918fa38795b60b18

**Comment by wb9688** [comment]
@coffeemakr: I didn't think about that, because I had to do this in 15 minutes (including booting my laptop) at the time. I've added your commit to this PR.

**Comment by wb9688** [comment]
Could this be merged now?

**Comment by theScrabi** [comment]
Merged tho would you mind adding some unit tests :)

**Pull request merged**
