### PR TITLE
use webm as format for opus audio streams

### PR DESCRIPTION
**Pull request by kapodamy**
**opus** suffix is only used if the container format is `ogg` but youtube delivers the audio in `webm` format.
This PR updates the itags in youtube extractor for `webm`

- [ ✔ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ✖ ] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ✔ ] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

### CODE REVIEW

**Comment by theScrabi** [comment]
I kind of messed this up when I didn't distinguish between stream and container format. This could one day be cleared up.

**Comment by kapodamy** [comment]
ok

**Comment by TobiGr** [comment]
Sorry for the delay. We should have merged this right after @theScrabi's approval.

**Comment by TobiGr** [comment]
@kapodamy Can you rebase it please?

**Comment by TobiGr** [comment]
We won't wait for the other PRs because their authors do not respond / apply the requested changes.

**Pull request merged**
