### PR TITLE
[YouTube] Switch to new search suggestion domain and improve error handling

### PR DESCRIPTION
**Pull request by AudricV**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).

- Switch to the new domain used by YouTube for search suggestions, `suggestqueries-clients6.youtube.com`, and add the `xhr` query parameter with the `t` value, to allow getting responses without requiring trim;
- Use the Java 8 Stream API to collect search suggestions and improve invalid response detection by checking whether the content type of the response returned is JSON;
- Improve `YoutubeSuggestionExtractorTest` and update its corresponding mocks.

### CODE REVIEW

**Comment by FireMasterK** [comment]
Would it make sense to fall back to the old search API if the new one fails? I've observed the new API being rate limited on Piped at times, so I think it could help.

**Comment by AudricV** [comment]
Isn't the same rate limit applied when you switch the search suggestion host? It happens for YouTube manifests.

**Comment by FireMasterK** [comment]
I've never really checked that, will see when I get rate limited again.

**Comment by FireMasterK** [comment]
It looks like the rate limits seem to be different, I tried the new search API on a rate-limited/blocked Piped node, and it worked when the old one failed.

**Comment by AudricV** [comment]
Ok, so what should we do? Pick a search suggestion host randomly?

**Comment by FireMasterK** [comment]
We could do that indeed. I was thinking we could store a static variable to store the last time we were rate limited as a `long`, and if been < 5 minutes, we use the old API. I can help with this if you'd like!

**Comment by FireMasterK** [comment]
It looks like I was using ipv6 on my testing, but my backends run on ipv4 only, the rate limit is also indeed on the new API, so I think this is ready to merge!

**Pull request merged**
