### PR TITLE
Use OkHttp's HttpUrl.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.
----
OkHttp's [`HttpUrl`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/) class offers greater functionality compared to the standard [`URL`](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html) class, such as a builder class for creating request URLs.

I created a relatively small changeset in this PR to get feedback on if the idea was sound, with more uses of `HttpUrl` to be added in future PRs.

### CODE REVIEW

**Comment by FireMasterK** [comment]
In my opinion, we should stick to `java.net.URL` for public methods (so that we don't break people's existing code). But, we can use HttpUrl for places where it adds benefits like query string parsing, like how you did using `queryParameter`.

**Comment by Isira-Seneviratne** [comment]
> In my opinion, we should stick to `java.net.URL` for public methods (so that we don't break people's existing code). 

I updated the existing methods to convert the `HttpUrl` objects to `URL` ones. I could add some additional methods to the code to avoid issues.

**Comment by FireMasterK** [comment]
> I updated the existing methods to convert the `HttpUrl` objects to `URL` ones. I could add some additional methods to the code to avoid issues.

Yes, currently for the methods/constructors you have changed, it should be fine. It's just for any future changes you may make.

**Review by acrodemocide — COMMENTED** [review]
Cool concept with the new URL library. How does it feel with the malformed URL exceptions? I saw catch statements replaced to catch an argument exception instead of a malformed URL exceptions, so I wasn't quite sure how those are handled with the new library.

The biggest risk I see is that if we start adopting it, is it something that we'll replace the entire app with soon? Or will there be enough pushback back on other pull requests so that we end up with some places using the old URL class and others using the new class? If we get buy in by the owners of the project and can get it replaced relatively quickly and easily, it could be a good addition to how URLs are managed.

**Comment by Stypox** [comment]
@Isira-Seneviratne from the IRC channel:
> I don't think we will merge neither Retrofit nor OkHttp in the extractor. Those are client side-libraries.

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne from the IRC channel:
> > I don't think we will merge neither Retrofit nor OkHttp in the extractor. Those are client side-libraries.

Thanks for the heads up.

**Comment by Isira-Seneviratne** [comment]
> Cool concept with the new URL library. How does it feel with the malformed URL exceptions? I saw catch statements replaced to catch an argument exception instead of a malformed URL exceptions, so I wasn't quite sure how those are handled with the new library.

It rethrows the MalformedURLException as an IllegalArgumentException.

> 
> The biggest risk I see is that if we start adopting it, is it something that we'll replace the entire app with soon? Or will there be enough pushback back on other pull requests so that we end up with some places using the old URL class and others using the new class? If we get buy in by the owners of the project and can get it replaced relatively quickly and easily, it could be a good addition to how URLs are managed.

**Comment by FireMasterK** [comment]
Maybe we should use an alternative URL parsing library? (Or, maybe we can create our own helper class)

I agree, okhttp is quite bloated if we just use it for parsing URLs

**Comment by Isira-Seneviratne** [comment]
> Maybe we should use an alternative URL parsing library? (Or, maybe we can create our own helper class)
> 
> I agree, okhttp is quite bloated if we just use it for parsing URLs

I added a few changes involving the construction of the URLs called in the extractor.

**Pull request closed without merging**
