### PR TITLE
Remove the need for a CommentsInfo instance in CommentsInfo.getMoreItems and fix PeertubeCommentsExtractorTest.Default test

### LINKED ISSUE #697: CommentsInfo.getMoreItems requires a CommentsInfo instance
Is this really necessary?

Would removing it affect other services?

### PR DESCRIPTION
**Pull request by FireMasterK**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

I also fixed the Peertube comments test.

Closes #697, this is important for Piped since these instances are currently cached in memory

### CODE REVIEW

**Review by Stypox — APPROVED** [review]

**Review by litetex — APPROVED** [review]
LGTM 

``commentsInfo.getCommentsExtractor().fetchPage();`` should be tested with NewPipe

**Comment by FireMasterK** [comment]
> `commentsInfo.getCommentsExtractor().fetchPage();` should be tested with NewPipe

I have built and tested this with NewPipe, and it worked perfectly. Are you referring to Unit tests? I think they can be added in a different PR

**Comment by litetex** [comment]
> I have built and tested this with NewPipe, and it worked perfectly. 

Ok, that's great. Then merge it is 😄

> Are you referring to Unit tests? I think they can be added in a different PR

No (there is already #813 for fixing these problems)

**Comment by litetex** [comment]
> I have built and tested this with NewPipe, and it worked perfectly. 

Ok, that's great. Then merge it is 😄

> Are you referring to Unit tests? I think they can be added in a different PR

No (there is already #813 for fixing these problems)

**Pull request merged**
