### PR TITLE
[YouTube] Fix playlist continuations extraction

### PR DESCRIPTION
**Pull request by XiangRongLin**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] ~~I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.~~

[app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5564833/app-debug.zip)

closes TeamNewPipe/NewPipe#4819

some random long playlist: https://www.youtube.com/playlist?list=PLABS9rhwbrHkrsit9lgHhx7MyqjJvj34C&list=UL

### CODE REVIEW

**Comment by FireMasterK** [comment]
Occurs when scrolling past the last item in the playlist.


## Exception
* __User Action:__ requested playlist
* __Request:__ https://www.youtube.com/playlist?list=PLYiFlG2SX5FfKCktcaV0z2DQLb_X-XGK7
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.20.2
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: JSON response is too short
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getValidJsonResponseBody(YoutubeParsingHelper.java:496)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:525)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.getPage(YoutubePlaylistExtractor.java:209)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getMoreItems(PlaylistInfo.java:37)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getMorePlaylistItems$10(ExtractorHelper.java:178)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$nPootHQm6SUQtGwsN1-hZ-V78xA.call(Unknown Source:6)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by XiangRongLin** [comment]
@FireMasterK That doesn't really help me since your removed the playlist id. so i can't reproduce it

**Comment by FireMasterK** [comment]
Here's one without it redacted:

## Exception
* __User Action:__ requested playlist
* __Request:__ https://www.youtube.com/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.20.2
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: JSON response is too short
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getValidJsonResponseBody(YoutubeParsingHelper.java:496)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:525)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.getPage(YoutubePlaylistExtractor.java:209)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getMoreItems(PlaylistInfo.java:37)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getMorePlaylistItems$10(ExtractorHelper.java:178)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$nPootHQm6SUQtGwsN1-hZ-V78xA.call(Unknown Source:6)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by XiangRongLin** [comment]
@FireMasterK I fixed the problem, could you try again with the updated apk at the top.

Problem was that a check for the end of the playlist was missing, when there are no more items. I added that and some tests to cover that case.

**Comment by FireMasterK** [comment]
The new apk seems to fail with "App not installed", I'm not sure why that is. 🤔

It's not a signature mismatch as I've uninstalled the previous build.

**Comment by XiangRongLin** [comment]
Try again now.

**Comment by FireMasterK** [comment]
Can confirm that it's fixed now! LGTM

**Comment by BenyBalazs** [comment]
It's working thanks.

**Review by TobiGr — APPROVED** [review]

**Comment by staticpatrick** [comment]
OMG thank you guys i just started looking for a fix and its already taken care of! now newpipe literally replaces youtube for my music purposes! yes!

**Pull request merged**
