### PR TITLE
Parse YouTube comments as HTML

### PR DESCRIPTION
**Pull request by FireMasterK**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

This change is to add support for clickable timestamps and URLs.

### CODE REVIEW

**Review by Stypox — APPROVED** [review]
Looks good to me, thanks!
@AudricV feel free to merge these small PRs without waiting for my or anyone's approval ;-)

**Comment by AudricV** [comment]
@Stypox I was not agree to merge this. `getCommentText` should return a plain text, not HTML (see PeerTube's `CommentsInfoItemExtractor` implementation).

Also, how NewPipe would handle this? It will probably display the comment with HTML tags.

If we want to return HTML, we should generalize the `Description` class, like already suggested, and return this class instead of a `String`.

**Comment by Stypox** [comment]
Well then write a comment if you already thought about this... When I looked at this PR I didn't find any comment saying it should not be merged...

Just like descriptions can come in many formats, can't comments do so too?

**Comment by FireMasterK** [comment]
> @Stypox I was not agree to merge this. `getCommentText` should return a plain text, not HTML (see PeerTube's `CommentsInfoItemExtractor` implementation).

Express that! Even if its just 1 line it helps.

> Also, how NewPipe would handle this? It will probably display the comment with HTML tags.

Descriptions currently are also HTML? Currently, I think it may do that. I think it should be easy to fix that?

> If we want to return HTML, we should generalize the `Description` class, like already suggested, and return this class instead of a `String`.

That could be done indeed. Would you like a PR for this?

**Comment by AudricV** [comment]
> Express that! Even if its just 1 line it helps.

I didn't have the time to do so and then I forgot a bit this PR, sorry!

> That could be done indeed. Would you like a PR for this?

Yes, it would be great!

**Comment by Stypox** [comment]
> I didn't have the time to do so and then I forgot a bit this PR, sorry!

That's fine, commits can be reverted anyway in case the Description PR takes some time ;-)

**Pull request merged**
