### PR TITLE
Niconico support

### PR DESCRIPTION
**Pull request by AioiLight**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Niconico (ニコニコ) is a video streaming service famous in Japan.
It is the birthplace of anime and game subcultures such as Oto-MAD (YTPMV), VOCALOID and Touhou.
It used to offer a service for English-speaking countries, but this has been discontinued and instead you can freely access the Japanese site.
As #719 mentioned, it is recommended for learners of Japanese, and since many non-verbal works have been uploaded, you can also view the videos as works of art.

Screenshots: 
| Trending | Search| Player |
| ---- | ---- | ---- |
| Screenshot_20220105-162615 | Screenshot_20220105-162639 | Screenshot_20220105-162709 |

Testing APK: (rename zip to apk)
[app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/7812868/app-debug.zip)

Remaing tasks:
- [ ] Support channel extracting of official channel
- [ ] Support audio-only streaming
- [ ] Support heartbeating
- [ ] More tests

Fixes: #719 TeamNewPipe/NewPipe#7437

### CODE REVIEW

**Comment by mhmdanas** [comment]
Hey @AioiLight, thanks for making this PR! The team is internally discussing whether they want to add Niconico, so can you please pause your commits for now to not have any more effort wasted if it's decided against?

**Comment by AioiLight** [comment]
@mhmdanas Thank you for telling about progressing discussion! I understand.

**Comment by opusforlife2** [comment]
Hey, @AioiLight. Thank you for your patience!

Unfortunately, the team has decided not to add Niconico support to Newpipe. But you're most welcome to fork the project, or try to see if another already existing Newpipe fork is willing to add it.

Thanks!

**Comment by AioiLight** [comment]
> Hey, @AioiLight. Thank you for your patience!
> 
> Unfortunately, the team has decided not to add Niconico support to Newpipe. But you're most welcome to fork the project, or try to see if another already existing Newpipe fork is willing to add it.
> 
> Thanks!

Hi @opusforlife2 , Thank you for replying! I understand what your team decided things.
I'm a little unfortunate, but I also think it's important for us to be careful about acepting new service.

**Pull request closed without merging**
