### PR TITLE
Add PeerTube HLS streams

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Duration is extracted, but not shown in the app correctly.

### CODE REVIEW

**Comment by TiA4f8R** [comment]
@TobiGr Does stream files are single?

**Comment by opusforlife2** [comment]
Crash when trying to open a related stream. Happens only occasionally, and the stream opens if you try again:

```
FATAL EXCEPTION: main
Process: org.schabi.newpipe.debug.peertubehls, PID: 7635
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter throwable
	at org.schabi.newpipe.error.ErrorInfo.<init>(Unknown Source:2)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$2.onLoadingFailed(VideoDetailFragment.java:690)
	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$2.run(LoadAndDisplayImageTask.java:360)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by TobiGr** [comment]
@opusforlife2 That stack trace does not help me. Can you try to get a full one?

**Comment by opusforlife2** [comment]
@tacothedank Is Scoop not providing a complete stack trace? ^

**Comment by opusforlife2** [comment]
@TobiGr It's one of those crashes where Newpipe's error activity does not open. So here's a logcat:

```
05-16 08:57:18.191 D/StateSaver(12221): onDestroy() called with: savedState = [24115478688811 > /storage/emulated/0/Android/data/org.schabi.newpipe.debug.peertubehls/cache/state_cache/24115478688811.7.list]
05-16 08:57:31.720 V/chatty  (12221): uid=10256(org.schabi.newpipe.debug.peertubehls) LeakCanary-Heap identical 1 line
05-16 08:57:34.010 E/AndroidRuntime(12221): Process: org.schabi.newpipe.debug.peertubehls, PID: 12221
05-16 08:57:34.011 E/ACRA    (12221): ACRA caught a NullPointerException for org.schabi.newpipe.debug.peertubehls
05-16 08:57:34.197 I/ActivityManager(1334): Start proc 12399:org.schabi.newpipe.debug.peertubehls:acra/u0a256 for service {org.schabi.newpipe.debug.peertubehls/org.acra.sender.JobSenderService}
05-16 08:57:34.362 I/WindowManager(1334): WIN DEATH: Window{86af451 u0 org.schabi.newpipe.debug.peertubehls/org.schabi.newpipe.MainActivity}
05-16 08:57:34.362 I/ActivityManager(1334): Process org.schabi.newpipe.debug.peertubehls (pid 12221) has died: vis+99 TOP 
05-16 08:57:34.576 W/ActivityTaskManager(1334): Activity top resumed state loss timeout for ActivityRecord{a539f13 u0 org.schabi.newpipe.debug.peertubehls/org.schabi.newpipe.MainActivity t-1 f}
05-16 08:57:35.346 I/stetho  (12399): Listening on @stetho_org.schabi.newpipe.debug.peertubehls:acra_devtools_remote
05-16 08:57:35.976 I/ACRA    (12399): Sending report /data/user/0/org.schabi.newpipe.debug.peertubehls/app_ACRA-approved/2021-05-16T08:57:34.056+05:30.stacktrace
05-16 08:57:36.106 I/ActivityTaskManager(1334): START u0 {flg=0x10000000 cmp=org.schabi.newpipe.debug.peertubehls/org.schabi.newpipe.error.ErrorActivity (has extras)} from uid 10256
05-16 08:57:36.109 W/ActivityTaskManager(1334): Background activity start [callingPackage: org.schabi.newpipe.debug.peertubehls; callingUid: 10256; isCallingUidForeground: false; isCallingUidPersistentSystemProcess: false; realCallingUid: 10256; isRealCallingUidForeground: false; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; isBgStartWhitelisted: false; intent: Intent { flg=0x10000000 cmp=org.schabi.newpipe.debug.peertubehls/org.schabi.newpipe.error.ErrorActivity (has extras) }; callerApp: ProcessRecord{128f75c 12399:org.schabi.newpipe.debug.peertubehls:acra/u0a256}]
```

**Comment by TiA4f8R** [comment]
> Is Scoop not providing a complete stack trace? ^

@opusforlife2 Taco answered you on the NewPipe IRC.

**Pull request merged**
