### PR TITLE
[WIP] Minified url of youtube videos NewPipe#1556

### PR DESCRIPTION
**Pull request by mjsir911**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).

I haven't gotten an opportunity to test this out due to not having a working android development environment yet, will get on that ASAP.

I don't see any pressing issues with change and I can't imagine how it would break anything.

I created the initial issue for this on the wrong repo: TeamNewPipe/NewPipe#1556

### CODE REVIEW

**Comment by wb9688** [comment]
I wouldn't do that, since the resulting URL would take a few ms more to load and Google will track that you've used youtu.be and there's no reason to do this.

**Comment by mjsir911** [comment]
Hi,

Would there be a more fitting place to shorten the youtube URL when the user actually has to interact with it through the `share` menu? See TeamNewPipe/NewPipe#1556 for more details, but i'm happy to help if i'm given a direction to go.

**Comment by wb9688** [comment]
Maybe you could create a new getShortenedUrl() function in StreamExtractor,
then implement it in YoutubeStreamExtractor and SoundcloudStreamExtractor
(just return null there, since SoundCloud doesn't have them). Then we also
have to add something to NewPipe to optionally share that minified link.

Op vr 27 jul. 2018 18:57 schreef Marco Sirabella <notifications@github.com>:

**Comment by mjsir911** [comment]
Sorry, I won't be able to accomplish this PR successfully.

I've looked into modifying `LinkHandlerFactory` to pass the short url to `LinkHandler`, which then passes it to `Info`, which can be accessed through `StreamInfo` in NewPipe's `VideoDetailFragment` `shareUrl()`

Thanks for trying to help, but the flow of the codebase is a bit too complex for me to file a quick PR that doesnt break more than it fixes

**Pull request closed without merging**
