### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by FireMasterK**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

This will automatically create PRs to keep dependencies up to date.

### CODE REVIEW

**Comment by Stypox** [comment]
Wouldn't this flood newpipe with PRs to merge?

**Comment by FireMasterK** [comment]
In a way, yes, but you can always ignore a dependency if you don't want to upgrade it.

**Comment by XiangRongLin** [comment]
Did you check if the test coverage and quality is high enough to merge those PRs without additional manual work?

**Comment by FireMasterK** [comment]
I'm not sure what exactly you mean, I would say the best way to evaluate these PRs is to check the changelog, check if it compiles, check if there's any breaking change, and then decide accordingly.

I'm not sure what tests would help in evaluating such PRs 🤔.

**Comment by XiangRongLin** [comment]
So that if there are any changes in the behavior of the library, we know it.

- Like if they accidently break their library and release it, we don't also break our library too.
- Or if we relied on some unintended behaviour, which got fixed in the library, but then breaks our functionality.

**Comment by FireMasterK** [comment]
That's a difficult question, I usually read the changelog to determine that. The only way to surely know is to test it otherwise.

**Comment by Stypox** [comment]
I'd merge this. Upgrading one thing at a time is a good idea amd we'd have to check changelogs anyway

**Review by B0pol — APPROVED** [review]

**Pull request merged**
