### PR TITLE
Cleanup: Remove old ways of getting YT dis/likes

### PR DESCRIPTION
**Pull request by litetex**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Some clean/followups after #753; Content
* Removed old way of getting likes (was disabled by YT - as predicted - on [2021-12-13](https://support.google.com/youtube/thread/134791097/update-to-youtube-dislike-counts))
* Removed dislike calculation because it no longer works (no average rating)
* Fixes Exception from #7525
* Deduplicated a ton of code inside the StreamExtractor(s) by using default/non-abstract methods
* Fixed tests

### CODE REVIEW

**Comment by opusforlife2** [comment]
I suppose it will have to be a hotfix.

**Comment by litetex** [comment]
I don't think we have to hotfix this as everything should still work as expected.
However this PR removes the code that by then will be (likely) irrelevant.
So this is just an improvement :)

**Comment by opusforlife2** [comment]
Oh, I was confused. The calculation method will still work.

**Review by TobiGr — APPROVED** [review]
Looks good.

**Pull request merged**
