### PR TITLE
[YouTube] Fix extracting the detailed error message for unavailable streams

### LINKED ISSUE #979: ContentNotFoundException doesn't extract reason correctly
Example: https://piped.video/watch?v=cWVEFcmtPjQ

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Fixes #979 
CC @FireMasterK

### CODE REVIEW

**Comment by FireMasterK** [comment]
I included this PR in Piped, but it doesn't seem to change anything there.
I will take a look further to see what's happening when I can later today.

**Review by acrodemocide — COMMENTED** [review]
Are there any unit tests we should add it update to help ensure that any code changes in the future don't reintroduce this bug?

**Comment by TobiGr** [comment]
I implemented those tests when I first created that kind of error detection, I think. However, the pages for videos which violated the TOS or were removed manually are deleted after ~2 months. That broke those tests quite frequently.

**Review by FireMasterK — APPROVED** [review]
I fixed it!

**Pull request merged**
