### PR TITLE
Implement time ago parser and improve localization handling

### PR DESCRIPTION
**Pull request by mauriciocolli**
Used some of the work that @wojcik-online did as the base, finishing the implementation of the time ago parser.

- Time ago parsing for stream items where the service shows it (search, channel videos list)
- Handle special cases for languages where the number is not shown
    - Hebrew, for example, shows "לפני שעתיים" for "2 hours ago". We cannot assume that it is 1 for those cases (popular among other languages), as it would be wrong in the bigger time units.
- Rework the Downloader base implementation, allowing for more advanced things to be done
    - Get the response headers
    - Response code status and message
    - Possibility of making other type of requests (`OPTIONS`, `HEAD`, `POST`...)
- Separate the localization from the content country (just like YouTube let's the user choose both).
- Parse watching count in live streams items
- Fix parsing of future videos (those with an option to set a reminder)

---

**Edit:** So I did see the PR #196 (related TeamNewPipe/NewPipe#2632), and as a result, no language parsing is needed anymore and english will be forced over others.

However, I think the language handling contained in this PR is still useful for NewPipe as we can now force languages easily and, in the future, help parse sites in other languages.

### CODE REVIEW

**Comment by theScrabi** [comment]
We need review and test on this. Someone willing to help?

**Comment by chetan00000007** [comment]
Sounds problem

**Comment by mauriciocolli** [comment]
I'll start to work on this again over the next few days (still have some catch up to do).

---

So I did see the PR #196 (related TeamNewPipe/NewPipe#2632), and as a result, no language parsing is needed anymore and english will be forced over others.

However, I think the language handling contained in this PR is still useful for NewPipe as we can now force languages easily and, in the future, help parse sites in other languages.

@TobiGr @Stypox @theScrabi

**Comment by Stypox** [comment]
Yes, this is useful, who knows what the future will bring :-)

**Comment by TobiGr** [comment]
Hey @mauriciocolli, welcome back!

> However, I think the language handling contained in this PR is still useful for NewPipe as we can now force languages easily and, in the future, help parse sites in other languages.

Yes, that functionality is a good addition. Please keep it.

**Comment by TobiGr** [comment]
That were a few lines to review :D Looks fantastic to me.

**Comment by mauriciocolli** [comment]
@TobiGr Oh, the temp commit (6ca4c89) went through. Sorry for the late reply.

**Comment by TobiGr** [comment]
@mauriciocolli Oh yes. I reverted it in 0c6e2c8f2356213843e7b04d6a55eb0f7099fa79

**Pull request merged**
