### PR TITLE
[Youtube] Make throttling decryption more resilient to api change

### PR DESCRIPTION
**Pull request by XiangRongLin**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

### CODE REVIEW

**Review by litetex — COMMENTED** [review]
Not sure how using static code is making the API more resilient...

I'm usually always against static stuff because it can't e.g. be overridden or simply reset by throwing away the related object.

**Comment by XiangRongLin** [comment]
The reason for it being static is, that the function and function name is always the same while the extractor is in use. Reason for THAT is that `YoutubeJavaScriptExtractor.extractJavaScriptCode(videoId);` is cached. So subsequent calls will always return the same results.
Knowing that it always is the same, I want to cache it. I don't see a way to cache it, beside making `FUNCTION` and `FUNCTION_NAME` static. And at that point the class has no member variables. So I made it static because I remeber reading an Android guide recommending not creating unecessary objects, since phones are very resource constrained.

---

> Not sure how using static code is making the API more resilient...

The static code has no relation to the resilience. The resilience comes from wrapping the whole decryption process in a try catch. It also does not make the API more resilient. It is making it more resilient against changes in the Youtube API

**Review by Stypox — COMMENTED** [review]
Code looks good to me. I agree with you about making things static, it's already being done in other places and it's good to cache the things needed for decryption.

Since the `YoutubeThrottlingDecrypter` is only meant for internal use, why deprecate things and not just remove them directly?

**Comment by XiangRongLin** [comment]
> Since the YoutubeThrottlingDecrypter is only meant for internal use, why deprecate things and not just remove them directly?

Because there is the n params cache, which had the reset method provided, which is meant to be used externaly. So who knows if somebody came to the idea to use the rest of the methods.

**Comment by XiangRongLin** [comment]
So anything blocking this? I would like to get this merged, so we don't get another fiasco like before because of this

**Comment by opusforlife2** [comment]
Use the request review button?

**Review by Stypox — APPROVED** [review]
Commit my small suggestion and then this is ready

**Review by Stypox — APPROVED** [review]

**Pull request merged**
