### PR TITLE
[YouTube] Fix the fetch of the video info page

### PR DESCRIPTION
**Pull request by TechComet**

### CODE REVIEW

**Comment by TobiGr** [comment]
please add a description telling us why this change is needed / which issue is resolved by it

**Review by TechComet — COMMENTED** [review]
add new pattern required `html5=1`

**Comment by TechComet** [comment]
This not work before add `html5=1`
`https://www.youtube.com/get_video_info?video_id=YudpwPkemzU&eurl=https://youtube.googleapis.com/v/YudpwPkemzU
`


This work after add `html5=1`
`https://www.youtube.com/get_video_info?video_id=YudpwPkemzU&html5=1&eurl=https://youtube.googleapis.com/v/YudpwPkemzU`

**Review by TiA4f8R — APPROVED** [review]
I think we should merge this, @TechComet is right: without the `html5` param, the request returns `404 Not Found`. @TobiGr What do you think?

**Comment by TobiGr** [comment]
@XiangRongLin I added you mock update commit. Was about to do generate them myself, but saw that you already did that :)

**Review by TobiGr — APPROVED** [review]
@TechComet Thank you

**Comment by XiangRongLin** [comment]
@TobiGr How the heck are you able to merge the PR inside his repo?!?

**Comment by opusforlife2** [comment]
He's a wizzzard. O.o

**Comment by opusforlife2** [comment]
@TechComet Always make sure to include a description of what feature your PR is adding or what bug it is fixing. Non-developers need to understand what the PR is doing as well.

**Pull request merged**
