### PR TITLE
[YouTube] Remove topStandaloneBadge check for view count of stream items

### PR DESCRIPTION
**Pull request by lonewolf2208**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).

Solved TeamNewPipe/NewPipe#9566

yt_stream_items_without_topStandaloneBadge_check

### CODE REVIEW

**Review by Stypox — APPROVED** [review]
I think this check can be removed safely, since if all of the below solutions fail, -1 is returned anyway

**Comment by AudricV** [comment]
@lonewolf2208 Please follow the template instructions, so we know that you agree to our contributions guidelines and that you've tested your changes. Thank you!

**Comment by lonewolf2208** [comment]
> @lonewolf2208 Please follow the template instructions, so we know that you agree to our contributions guidelines and that you've tested your changes. Thank you!

Okay done @AudricV

**Comment by AudricV** [comment]
Thanks, note that we will handle the extractor update ourselves.

**Pull request merged**
