### PR TITLE
Do not list YouTube's OTF streams

### PR DESCRIPTION
**Pull request by wb9688**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Ignore streams that are delivered using YouTube's OTF format, as those only work with DASH and not with progressive HTTP.

### CODE REVIEW

**Comment by Stypox** [comment]
Does this remove the streams causing infinite loading?

**Comment by wb9688** [comment]
@Stypox: Yes, that's what this PR is for.

**Comment by Stypox** [comment]
@TobiGr I'd merge this in 0.20.0 to bring better stability, it is such a small change

**Review by Stypox — COMMENTED** [review]
Do you think we should add a test for this? Maybe we can do without, if you tested well, since this code is going to be removed anyway in the future

**Comment by TobiGr** [comment]
Stuff like this should be done in the frontend and not the extractor. We can merge this now, but IMO we should extract all itags and provide all stream formats through the extractor. The frontend needs to sort out unsupported formats.

**Comment by wb9688** [comment]
@TobiGr: No. Currently NPE is supposed to only return progressive HTTP streams (and sometimes a torrent as well). These streams aren't progressive HTTP, so NPE shouldn't return them. There is also not really a proper way how NP could figure that out. With my DASH/HLS support PR, there will be a way to specify what kind of streaming method should be used, and then a frontend should skip e.g. DASH streams if they don't support that. However that's not the case yet. After I finish that PR and that gets merged, I'll make a PR extracting all itags based on the metadata that YouTube provides, which could include e.g. 360° videos, which should then also be filtered out by frontends not supporting that.

**Review by TobiGr — APPROVED** [review]
Looks good to me.
I do not have time to write tests for this PR, @wb9688 hasn't either. Let's merge this and wait until @wb9688 finishes #367

**Pull request merged**
