### PR TITLE
Refactor extractor

### LINKED ISSUE #6: Remove static variables from extractors
As I said [here (comment)](https://github.com/TeamNewPipe/NewPipeExtractor/pull/5#issuecomment-296312218), we need to remove these static variables, because (among another reasons) let's say that I want to extract multiple channels at the same time, with the current static variables one "instance" will interfere with the other, not pretty...

[Here](https://gist.github.com/mauriciocolli/8ac78739bc4b316f6a947f3cc3ce52ea)'s a gist demonstrating that.

PS: Another problem is that you can't request a specific page from a channel, but let's fix that after this is fixed.

### PR DESCRIPTION
**Pull request by mauriciocolli**
- Create some abstract classes to minimize repeated code
    - `Extractor` and `Info`
- Channel and Playlist extractors have a `getNextStreams` method now
    - Fix channel's feed URL (closes TeamNewPipe/NewPipe#585)
- Organize some packages and classes
    - Rename package `stream_info` to just `stream`
- Refactor and fix indentation in general

Closes #6

### CODE REVIEW

**Comment by theScrabi** [comment]
Can you please send a coresponding pull request for NewPipe itself. NewPipe is not yet able to handle the refactored code.

**Comment by mauriciocolli** [comment]
I'm not finished in the NewPipe side (maybe this weekend), but you can already merge it, just let the submodule in NewPipe pointing to the latest commit until now (ab530381cfb5cc3278f1c4f63f30b33ca3d54d5d), but it's up to you to decide...

**Comment by theScrabi** [comment]
@mauriciocolli I thought about this pull request, and I think you are good to merge :)

**Comment by theScrabi** [comment]
@mauriciocolli all right please merge :)

**Pull request merged**
