### PR TITLE
Downgrade Rhino since it uses a class not available on Android

### PR DESCRIPTION
**Pull request by Stypox**
Reverts #774
Fixes TeamNewPipe/NewPipe#8876
See https://github.com/mozilla/rhino/issues/1149 for why this is needed

### CODE REVIEW

**Review by AudricV — APPROVED** [review]

**Comment by Stypox** [comment]
I tested and it actually works

**Comment by leslie-alldridge** [comment]
Legend @Stypox
To get this fix do we check for updates in app or is there a dev build we should download? Cheers

**Comment by Theta-Dev** [comment]
I have already made a debug build which includes thia fix as well as a JS extractor change

https://github.com/TeamNewPipe/NewPipe/files/9387795/app-debug.zip

**Comment by nontekkie** [comment]
I am not a developer (far from it), but I came here because my NewPipe app keeps breaking. Is the link above (https://github.com/TeamNewPipe/NewPipe/files/9387795/app-debug.zip) the fix I need if videos load infinitely? If so,  once I download it, do I have to perform more steps, or will the download automatically modify my app? Thanks

**Comment by nontekkie** [comment]
Thanks. I've been waiting for an update from my app store, but it hasn't been released yet. (I use a Murena Teracube running a non-Android OS forked from Lineage. These phones have an app suite with open source apps and also Google apps.) I tried to download the latest update from the NewPipe website, but that was unsuccessful. Any other suggestions?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by leslie-alldridge** [comment]
Lol your setup sounds overly complicated. Don't bother with an app store just download directly from their website. If that doesn't work you need to allow apps from unknown sources. If that fails, I doubt there's a terracube custom os specialist so you're probably on ya own

**Pull request merged**
