### PR TITLE
Fix OkHttp

### PR DESCRIPTION
**Pull request by wb9688**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

This commit fixes OkHttp support. All unit tests still pass with HttpsUrlConnection. Should I replace the test `Downloader.java` with OkHttp support or should there be 2 test variants (1 with HttpsUrlConnection and 1 with OkHttp)? I'll also create a PR to NewPipe to add OkHttp support and use the new NewPipeExtractor API.

### CODE REVIEW

**Comment by theScrabi** [comment]
If it was easy to do please add tests for both.

**Comment by wb9688** [comment]
>If it was easy to do please add tests for both.

I don't know enough about Gradle for that, maybe @mauriciocolli knows how to do that. If not, should I just use OkHttp for the tests?

**Comment by theScrabi** [comment]
I guess you can introduce it.

**Comment by mauriciocolli** [comment]
I just figured why OkHttp didn't work right way, the cause is this: [Downloader.java#L118..L120](
https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/src/test/java/org/schabi/newpipe/Downloader.java#L118..L120).

You can notice that this is removing all the line separators, instead, it should be just copying the bytes from the InputStream, which is probably what OkHttp is doing.

This _may_ break other things in NewPipe, but it's for the better. And I really like the idea of using OkHttp as the downloader as we'll have some nice features like retry (useful in unstable networks) and better yet, we will know that we are using the same implementation across all devices (which _may_ not be true for the java implementation because of API version, java version, manufacturer, etc.)

**Comment by theScrabi** [comment]
> You can notice that this is removing all the line separators

I see. Well than newpipe needs to be able to work without line separators.

**Comment by wb9688** [comment]
@theScrabi: Uhmm… that's what I fixed in this PR ;)

**Comment by theScrabi** [comment]
> @theScrabi: Uhmm… that's what I fixed in this PR ;)

I see :D.

**Comment by theScrabi** [comment]
Why are the unit tests failing?

**Comment by wb9688** [comment]
@theScrabi: On my PC, they aren't failing. On Travis, this is just one of
these times it's incorrectly failed with the search extraction (it expected
a channel, but it was a video), which can't be a result of this code, since
this doesn't touch that part at all.

**Pull request merged**
