### PR TITLE
Fix YouTube videos with no views

### PR DESCRIPTION
**Pull request by wb9688**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

Fixes TeamNewPipe/NewPipe#3238

### CODE REVIEW

**Comment by Stypox** [comment]
@wb9688 what happens in other localizations? I would put a check on the result of `Utils.removeNonDigitCharacters(views)`: if it is an empty string I think it would be safe to return 0, as "No views" and hopefully all of its translations do not contain digits.

**Comment by wb9688** [comment]
@Stypox: There are multiple places where we use localized strings, e.g. https://github.com/wb9688/NewPipeExtractor/blob/cb57123be199dd1633776e65020fae487692a1f5/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java#L243. @B0pol said he gave up on supporting localized YouTube sites though.

**Comment by Stypox** [comment]
I know localized YouTube is not correctly supported, but since there is the opportunity not to introduce another dependency on English, let's not do it ;-)

**Comment by gzsombor** [comment]
I've run into the same issue - independently - and fixed this way: https://github.com/TeamNewPipe/NewPipeExtractor/pull/294

**Comment by wb9688** [comment]
Updated PR to use same approach as in YoutubeStreamInfoItemExtractor.

**Comment by Stypox** [comment]
@TobiGr oh, I was about to do it, I already added the change to the changelog ;-)

**Comment by TobiGr** [comment]
I added it, too. Maybe I have overridden it :laughing:

**Pull request merged**
