### PR TITLE
[YouTube] Cache deobfuscation code and more fixes

### PR DESCRIPTION
**Pull request by Stypox**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).

### ~~YouTube's changes :-D :-D~~
~~Apparently YouTube stopped providing obfuscated URLs completely! This solves many problems in the `YouTubeStreamExtractor`, since now there won't be any "could not deobfuscate ..." exception and loading will be much faster. I don't know the reason for this change, but I ran every `YouTubeStreamExtractor*Test` more than 50 times each, all without errors :-D. Btw, this PR also includes (as a standalone commit which should then be squashed, as it does not make sense) my first attempt at speeding up the fetching process, i.e. caching player urls, which are now not needed anymore at all.~~

### In more detail:
- Cache deobfuscation code and only make the request to get it if needed
- Fix age restricted videos, and correctly determine age limit
- Solve a couple of Andoid Studio warnings
- Do not extract subtitles in `onFetchPage()`, but only when requested
- Parse upload date for livestreams and ended livestreams
- Improve falling back to video info page in case something is missing from `initialAjaxJson`
- Add `assertNotNull` on related streams if they are expected in `DefaultStreamExtractorTest`

### Fixes

- Fixes TeamNewPipe/NewPipe#4681
- Fixes TeamNewPipe/NewPipe#3336

### Testing apk

Since I don't know whether this change is there all over the world, here is an apk for all of you to test. Please try to test it under many different network conditions.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5469230/app-debug.zip)
@opusforlife2 could you link here users that encountered problems with youtube streams in 0.20.1? So that we have many people to test this ;-)

### CODE REVIEW

**Comment by opusforlife2** [comment]
It seems to have broken DASH videos. I mean those where we've removed OTF streams and are only left with 360p and maybe 1080p.

**Comment by opusforlife2** [comment]
Do we have any DASH videos in our tests?

**Comment by xibr** [comment]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=zWRUx0U1aNk
* __Content Country:__ KR
* __Content Language:__ ko
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.20.2
* __OS:__ Linux samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUAETG3:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by B0pol** [comment]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=wMBNpVQ0k_k
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.20.2
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by Stypox** [comment]
Thank you, that's reproducible. I'll look into it later

**Comment by opusforlife2** [comment]
Hi dEvS! Great App! Very nice!!11! New updare wHEN? :D

**Comment by Stypox** [comment]
I readded obfuscation code, and added caching for it: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5469230/app-debug.zip)

**Comment by opusforlife2** [comment]
This apk wants to install over the apk from your fix-detail-open branch.

**Comment by Stypox** [comment]
> This apk wants to install over the apk from your fix-detail-open branch.

Oh, yes, I built it using that base code, hope that's not a problem ;-)

**Comment by opusforlife2** [comment]
Well, seeing as I'm testing both... it kind of is a problem. 🤐

**Comment by xibr** [comment]
So far it works fine.

**Comment by cmomoney** [comment]
Seems to be working for me. Thanks.

**Comment by Stypox** [comment]
An apk containing both VideoDetailFragment fixes TeamNewPipe/NewPipe#4562 and deobfuscation improvements TeamNewPipe/NewPipeExtractor#447, in case someone (@opusforlife2) wants to test both at the same time: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5473958/app-debug.zip)

**Comment by opusforlife2** [comment]
Wut bout seprate APK here?

**Comment by Stypox** [comment]
Why would you need that? Here you just need to test that all videos work, not if the app runs faster or whatever

**Comment by opusforlife2** [comment]
So I need an apk that is org schabi newpipe debug, or an apk named with this PR's branch name. The APKs you're uploading are named with the fix-video-details branch name, which is another actively updated PR I'm testing as well. So I need to be able to install them side by side. That's what I meant here https://github.com/TeamNewPipe/NewPipeExtractor/pull/447#issuecomment-720063453.

**Comment by Stypox** [comment]
Here you are: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5477759/app-debug.zip)

**Comment by xibr** [comment]
The video cannot be played with toast message "could not play this stream"
https://youtu.be/7TseTFjNd1Y in Release 0.20.2 It works without any problem.

Same issue  [#3336](https://github.com/TeamNewPipe/NewPipe/issues/3336) ?!

**Comment by opusforlife2** [comment]
I get this error on nearly every video. Strangely, not on live videos, or videos that used to be live. @xibr Was yours a live video at some point? I don't get the date parsing error on it. And it opens just fine for me, no error. Try it again.

The videos open just fine. I just get an error snackbar.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=KNuMnNjnOGg
* __Content Country:__ CH
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.20.2
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse date: "2020-10-03"
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.parseDateFrom(YoutubeParsingHelper.java:187)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getUploadDate(YoutubeStreamExtractor.java:190)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:266)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: j$.time.format.DateTimeParseException: Text '2020-10-03' could not be parsed at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at j$.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at j$.time.OffsetDateTime.parse(OffsetDateTime.java:402)
	at j$.time.OffsetDateTime.parse(OffsetDateTime.java:387)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.parseDateFrom(YoutubeParsingHelper.java:185)
	... 30 more

```
</details>
<hr>

**Comment by xibr** [comment]
I cannot play videos that were previously broadcast live.
https://youtu.be/OWJHyYKVcoE
https://youtu.be/dAIBDfzrzJk

> The videos open just fine. I just get an error snackbar.
 it happens with me only with this apk 
> Here you are: app-debug.zip
Does not happen on the apk provided in the first comment.

**Comment by Stypox** [comment]
@opusforlife2 that's caused by updating to java 8 and will be fixed by @Isira-Seneviratne 
@xibr ok, I guess I'll have to revert to the old way of detecting livestreams

**Comment by Isira-Seneviratne** [comment]
@Stypox I added a commit fixing the parsing issue to [this PR](https://github.com/TeamNewPipe/NewPipeExtractor/pull/454).

**Comment by opusforlife2** [comment]
> I cannot play videos that were previously broadcast live.

Ah, you're right. I was just assuming that since video details opened fine there was no error. But yeah, trying to play previously live streams fails with that toast.

However, currently live videos play fine, @Stypox.

**Comment by Stypox** [comment]
@xibr @opusforlife2 I fixed problems with livestreams by reverting the way they are detected:
- NewPipe's `fix-details-view` branch: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5488427/app-debug.zip)
- NewPipe's `dev` branch: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/5488454/app-debug.zip)
<sub>The two APKs have the same extractor implementation, so test *only one* of those. If you choose the first one you can test both this changes and those in TeamNewPipe/NewPipe#4562 at once.</sub>

**Comment by xibr** [comment]
no issues about parse date now, and live streams problems work as well.

**Comment by opusforlife2** [comment]
Yup. All 3 kinds of videos work: live streams, previously live streams, and normal videos.

**Comment by Stypox** [comment]
This fixes #3336, I tested with a livestream that had just ended and, even though such streams are still considered as running livestreams (which are played as DASH by the NewPipe player), there are no errors anymore since the DASH url is extracted correctly and such videos are detected correctly.

**Comment by B0pol** [comment]
TeamNewPipe/NewPipe#3336

**Review by TobiGr — APPROVED** [review]
Looks good.
Next time, please make more commits, E.g. "Automatically fix more things" and "fix age restriction extraction" could have been in separate commits. That speeds up the review process.

**Pull request merged**
