### PR TITLE
Allow PlayLists with missing uploader

### PR DESCRIPTION
**Pull request by Redirion**
This supports PR [2724](https://github.com/TeamNewPipe/NewPipe/pull/2724) in NewPipe

For bug description and proposed solution with this pr, see this [comment](https://github.com/TeamNewPipe/NewPipe/pull/2724#issuecomment-562844521).

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [X] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

### CODE REVIEW

**Comment by PeterHindes** [comment]
Nice I'll test a build with these changes later today.

**Comment by PeterHindes** [comment]
what is the proper way to run a test build with this version of the extractor. Im unfamiliar with gradle.

**Comment by Stypox** [comment]
@PeterHindes open up the project in Android Studio and create a new run configuration for Junit 4 tests

**Comment by PeterHindes** [comment]
I meant building it with the app. I was tryna add it here

**Comment by Stypox** [comment]
@PeterHindes follow these steps:
1. Go to the root `build.gradle` file (in the project root folder) and add `maven { url "https://jitpack.io" }` under  `allprojects { repositories { ... HERE } }`
2. Go to the app `build.gradle` file (in the app/ subfolder) and add `implementation 'com.github.USERNAME:REPO_NAME:FULL_COMMIT_SIGNATURE'`. For the latest commit of @Redirion repository it would be `implementation 'com.github.Redirion:NewPipeExtractor:cdf41b868c5ea877fd6e1e90688f0d4e95c84a34'`.

**Comment by PeterHindes** [comment]
cool thanks for walking me through it. for future refrence where did you get the 

> cdf41b868c5ea877fd6e1e90688f0d4e95c84a34

from?

**Pull request merged**
