### PR TITLE
Pass additional regexes to youtube extractor

### PR DESCRIPTION
**Pull request by nik-vanderveen**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

Adds support for passing additional regexes (from file, server, etc.) through youtube's extractor in order to fix extraction errors without an update. Closes TeamNewPipe/NewPipeExtractor#255

### CODE REVIEW

**Comment by TobiGr** [comment]
Thank you. Is there a reason why @nik-vanderveen creates a PR from @CWftw's repo?

**Comment by CWftw** [comment]
> Thank you. Is there a reason why @nik-vanderveen creates a PR from @CWftw's repo?

I am CWftw and I approve this message

**Comment by B0pol** [comment]
It has both a benefits and downsides:
:ok_hand: people will be able to add the regex found somewhere in settings
:+1: less people would leave NewPipe due to it being broken
:-1: people will be able to stay on an old version, without the other bug fixes…

I'm totally for this possibility.

**Comment by opusforlife2** [comment]
Have you guys discussed how this should be presented to the user?

My instinct as a user is to basically have a tappable option in settings to download additional regexes which you could host on the Newpipe website. All it would do is present a toast whether the download succeeded or failed, and people should see their videos opening again.

Where the downloaded file goes is inconsequential to the end user, though it should probably be part of the app's internal storage so that even if a user doesn't grant storage permission to Newpipe, the functionality doesn't break.

**Comment by litetex** [comment]
I'm closing this for now:
* no progress since over a year
* merge conflicts
* PR is in the current form no longer applicable. There have been massive reworks in the Extractor in the meantime (e.g. #604) and the suggested fixes with the regex e.g. won't solve #683

Feel free to reopen when there is progress again

**Pull request closed without merging**
