### PR TITLE
Fix/yt decryption

### LINKED ISSUE #241: Can't play any YouTube video / Could not parse decrypt function
See https://github.com/TeamNewPipe/NewPipe/issues/2981
and the crash report:
https://github.com/TeamNewPipe/NewPipe/issues/2981#issuecomment-577840425

### PR DESCRIPTION
**Pull request by TobiGr**
Fixes #241 
Fixes https://github.com/TeamNewPipe/NewPipe/issues/2981
Thanks to @stvpn for helping with the regex which was originally taken from https://github.com/ytdl-org/youtube-dl/commit/c3cfea906869e8358652e382679a5996c2aec73e

### CODE REVIEW

**Comment by TobiGr** [comment]
Oh wait, I put the commits on top of the wrong branch

**Comment by Lhotse2** [comment]
App was not installed. What is going on?

**Comment by TobiGr** [comment]
https://newpipe.schabi.org/FAQ/download/ 
See the entry "Upgrading NewPipe fails"

**Comment by Lhotse2** [comment]
Solved! Thanks so much Tobias!

**Comment by pythonInRelay** [comment]
It doesn't seem to be available on F-Droid yet? I wish you guys would just give us a direct apk link.

**Comment by justanidea** [comment]
https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.18.2

**Comment by pythonInRelay** [comment]
Mate you are a legend. ❤️

**Comment by akgdkal** [comment]
I am a fan of the app but in its latest update the background blocks the app and even the mobile

**Comment by beskhu3epnm** [comment]
Why did it take so long for you to update the F-Droid page?

**Comment by Stypox** [comment]
We didn't do anything, the bottleneck is the F-Droid server that has to build and check signatures

**Comment by beskhu3epnm** [comment]
I suggest you put a little message with a hyperlink informing others to check for the latest release from the GitHub page if there are problems.

**Pull request merged**
