### PR TITLE
fix comment url

### PR DESCRIPTION
**Pull request by yausername**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

required for https://github.com/TeamNewPipe/NewPipe/pull/2168

### CODE REVIEW

**Comment by yausername** [comment]
I have been raising PRs for master branch till now. Should we switch to dev branch in the extractor also?

**Comment by theScrabi** [comment]
Yes

**Comment by yausername** [comment]
I have changed the base branch to dev now. This PR also includes a couple of other changes that were merged to master but not dev.

**Comment by theScrabi** [comment]
Is dev and master not up to date?

**Comment by yausername** [comment]
> Is dev and master not up to date?

No. master is 5 commits ahead of dev.  This PR will fix that though.

**Comment by theScrabi** [comment]
Ok

**Pull request merged**
