### PR TITLE
Update nanojson

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Update our fork of nanojson. This includes a few dependency updates as well as smaller improvements from upstream.

### CODE REVIEW

**Review by litetex — COMMENTED** [review]
2 points I have to discuss here:
1. All tests are failing there seems to be something wrong
2. What are the changes in the new "version"?

**Comment by FireMasterK** [comment]
I just want to add that the current fork of nanojson uses significantly more CPU than upstream!

In Piped, I'm now using a personal fork since https://github.com/TeamPiped/Piped-Backend/pull/357, the difference is *MASSIVE*! (probably well within )

I did this after seeing that nanojson was using a lot of CPU in the `nextToken` method. The NewPipe fork has changes, calling this method more times (for JS parsing?), which could be the cause of this.

I don't have a before, but here's the after (it was ~1800 seconds before, within 10 minutes):
After:
image

**Comment by opusforlife2** [comment]
@FireMasterK If the only difference between this version and your fork is upstream changes, could they not be added to this fork?

**Comment by FireMasterK** [comment]
> @FireMasterK If the only difference between this version and your fork is upstream changes, could they not be added to this fork?

I suppose they could, but I only tested it on YouTube (in Piped), I'm not sure if other services require the JS json extraction. In my fork, I have the upstream changes and have cherry-picked only this commit: https://github.com/TeamNewPipe/nanojson/commit/d5da581ec79e6cc12962da8b92749038143f8e08

**Comment by Stypox** [comment]
Closing in favor of  #981

**Pull request closed without merging**
