### PR TITLE
Fix parsing new ytInitialData

### PR DESCRIPTION
**Pull request by wb9688**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Fixes TeamNewPipe/NewPipe#4201

### CODE REVIEW

**Review by Stypox — APPROVED** [review]
The regex looks good (I was about to push a PR, too ;-) )

**Comment by opusforlife2** [comment]
Test APK. (づ｡◕‿‿◕｡)づ

**Comment by opusforlife2** [comment]
> The base branch was changed.

Hotfix, @TobiGr?

**Comment by wb9688** [comment]
Why even? There are only bug fixes in dev: https://github.com/TeamNewPipe/NewPipeExtractor/compare/v0.20.0...dev

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
