### PR TITLE
[YouTube] Fix music mixes in some countries

### PR DESCRIPTION
**Pull request by Stypox**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Fixes https://github.com/TeamNewPipe/NewPipeExtractor/pull/788#issuecomment-1053910554

I have no idea if this really fixes the issue, but @opusforlife2 you could give it a try, here is an APK: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/8165075/app-debug.zip) ;-)

### CODE REVIEW

**Comment by opusforlife2** [comment]
Ahaha... It 'fixed' the problem in an unexpected way. Now there are no more Mixes to even get an error. 😆

**Comment by Stypox** [comment]
@opusforlife2 well, just share a mix from the other app or directly from youtube ;-)

**Comment by opusforlife2** [comment]
Ah. Success!

**Comment by Stypox** [comment]
Oh, great, I didn't really except this fix to work ;-)
Then this PR is ready

**Comment by opusforlife2** [comment]
Shouldn't this code be merged into the other PR? I've never seen an unmerged PR being fixed by another PR. You guys usually force-push.

**Comment by Stypox** [comment]
@opusforlife2 no, this PR fixes mixes in general, it has nothing to do with the other PR that adds mixes to related items

**Comment by Stypox** [comment]
@XiangRongLin could you also review and merge this, please?

**Review by XiangRongLin — APPROVED** [review]

**Comment by opusforlife2** [comment]
Thank you so much!

**Pull request merged**
