### PR TITLE
Fix Youtube likes + disable dislikes

### PR DESCRIPTION
**Pull request by litetex**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API. → No changes required, only a extractor update

This PR provides a fix for https://github.com/TeamNewPipe/NewPipe/issues/7405:
* It fixes the extraction of the likes
* Disables extraction of dislikes
* Fixed some related tests
* Updated mock data

Fixes https://github.com/TeamNewPipe/NewPipe/issues/7405

Preview for NewPipe:
grafik

### CODE REVIEW

**Comment by B0pol** [comment]
We should still extract dislikes when available and disable them on December 13th https://developers.google.com/youtube/v3/revision_history

**Comment by opusforlife2** [comment]
Maybe the UI could be tweaked a little bit now that there is some empty space there.

**Comment by B0pol** [comment]
> Maybe the UI could be tweaked a little bit now that there is some empty space there.

You should open a feature request on NewPipe :) but it’s not required for this PR

**Comment by TiA4f8R** [comment]
Closing in favor of #753.

**Comment by litetex** [comment]
Reopeing:
1. The other PR doesn't have working tests
2. The code in the other PR will be irrelevant in a few weeks. According to https://support.google.com/youtube/thread/134791097/update-to-youtube-dislike-counts YT's API will stop delivering dislike counts on 2021-12-13; That will also likely be the date the currently running A/B test will be finished an no more requests will be answered with the dislike count.

**Comment by B0pol** [comment]
> Reopeing:
> 
>     1. The other PR doesn't have working tests

Please check logs:
> org.schabi.newpipe.extractor.services.bandcamp.BandcampSearchExtractorTest$DefaultTest > testRelatedItems FAILED
> 1635 tests completed, 1 failed, 122 skipped

unrelated failing test is not my fault

>     2. The code in the other PR will be irrelevant in a few weeks. According to https://support.google.com/youtube/thread/134791097/update-to-youtube-dislike-counts YT's API will stop delivering dislike counts on 2021-12-13; That will also likely be the date the currently running A/B test will be finished an no more requests will be answered with the dislike count.

Then IMO we should remove it when it’s not available anymore.

**Comment by litetex** [comment]
@B0pol 
Touché.

At first, this PR is a draft because YT is still A/B testing the new changes.

If I understand your PR correctly, it
* tries to get the likes the old way style and if that fails it uses the new way
* ties to get the dislikes the old way style and if that fails it calculates them using ``averageRating`` (which is - unexpectedly - very accurate: grafik)

If that is correct I think we should go with your PR instead.
However we should do an additional fix once the "old" ways doesn't work anymore (likely in ~1month or so).

**Comment by litetex** [comment]
Closing in favor of #753.

**Pull request closed without merging**
