### PR TITLE
add vscode / eclipse files to .gitignore

### PR DESCRIPTION
**Pull request by B0pol**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

This would save me lots of `git clean -d -f` when I just wanna quickly check a file in vscode.

### CODE REVIEW

**Comment by Stypox** [comment]
Shouldn't you also add `*.vscode/`?

**Comment by B0pol** [comment]
> Shouldn't you also add `*.vscode/`?

I've never encountered this file and it seems they doesn't exist by looking on internet.

**Comment by wb9688** [comment]
See:

- https://github.com/github/gitignore/blob/master/Java.gitignore
- https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore
- https://github.com/github/gitignore/blob/master/Global/Eclipse.gitignore
- https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

Obviously we shouldn't add the things that are irrelevant to us.

**Comment by B0pol** [comment]
> Obviously we shouldn't add the things that are irrelevant to us.

Yes, that's why I won't add `.vscode`, it's irrelevant. It's not doing that when I use vscode. If it does, someone can open another PR.

**Comment by Stypox** [comment]
> > Shouldn't you also add `*.vscode/`?
> 
> I've never encountered this file and it seems they doesn't exist by looking on internet.

This is the folder containing all vscode configuration for a project, how can you have never seen it? See https://code.visualstudio.com/docs/getstarted/settings

**Comment by B0pol** [comment]
I don't now, i just press `code newpipe` or `code newpipeextractor`, or open folver via GUI. I'll try with vanilla vscode.

**Comment by B0pol** [comment]
I've tried with vanilla vscode.
1. I've never used workspaces, but just used `open folder`. That may be a reason why.
2. I've tried to change some settings, and it was asked to create a .code-workspace file, but it didn't created any `.vscode` folder

**Comment by B0pol** [comment]
Can this be merged?

**Comment by wb9688** [comment]
Quoting what I said on IRC:

>No, I didn't approve the NPE one for a reason:  **/bin should be bin/ and  **.vscode should be .vscode/

>In .gitignore, it'll match any directory called "bin" with "bin/". "/bin/" would make it relative to the .gitignore file. So "\*\*/bin" is pointless. "**.vscode" seems to do the same thing as "*.vscode", but the folder is always just called ".vscode", so you should just do ".vscode/". When it has a "/" at the end, it'll only match directories with that name instead of all inodes with that name, but it mainly makes it clearer to anyone reading it whether that's supposed to be a file or a folder.

**Pull request merged**
