### PR TITLE
Un-comment out 360p webm

### PR DESCRIPTION
**Pull request by XiangRongLin**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] ~~I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).~~ No, see https://github.com/TeamNewPipe/NewPipe/issues/5363

 apk https://github.com/XiangRongLin/NewPipe/actions/runs/472076189

@Redirion

### CODE REVIEW

**Comment by opusforlife2** [comment]
Why is the build-and-test action failing?

**Review by Redirion — APPROVED** [review]

**Comment by XiangRongLin** [comment]
@opusforlife2 It's been failing for a very long time because part of the extractor is simply broken or the tests are broken.


See #481 for more information and the linked PR where i try to address it. But haven't really gotten much feedback so i guess it is going to stay like stay for a while

**Comment by Redirion** [comment]
@TobiGr this is a trivial change, tested by a few people already. Please merge.

**Review by TobiGr — APPROVED** [review]
I don't remember the reason, by that specific codec was commented out on purpose. However, I did not find any bugs with the current player implementation, so I'll merge this PR.

**Comment by opusforlife2** [comment]
> I don't remember the reason, by that specific codec was commented out on purpose.

@TobiGr I think it was before magic man kapodamy implemented merging of video-only + audio-only streams for downloading. You could only download video-only streams, so there needed to be at least one format that would have sound in it, and that was the 360p mp4.

**Pull request merged**
