### PR TITLE
Upgrade Gradle to 7.1.1

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Upgrade Gradle to 7.1.1

Closes TeamNewPipe/NewPipe#6651

### Todo:
- [ ] check if anything broke
- [ ] Go though upgrade guide and check deprecations / API changes

### CODE REVIEW

**Comment by litetex** [comment]
LGTM

Can this be switched to "ready for reviewing" or are there any things speaking against it?

**Comment by TobiGr** [comment]
I did not have time to check the upgrade notes. Ill do it later

**Comment by XiangRongLin** [comment]
@TacoTheDank do you have time to do this? since you already went through this process once, you should know what to look out for

**Comment by TacoTheDank** [comment]
@XiangRongLin Sorry for late reply. Sure, I'll look into it :) should I do a separate PR?

**Comment by TobiGr** [comment]
@TacoTheDank Feel free to do so

**Comment by TacoTheDank** [comment]
@TobiGr this can be closed, I believe

**Comment by TobiGr** [comment]
thanks

**Pull request closed without merging**
